//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealCloud.AddIn.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DealCloud.AddIn.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a new version of the Add In.  Please close and reopen [Outlook, Word or Excel] to update the DealCloud Add In to the latest version..
        /// </summary>
        public static string Addin_Login_Vesrion_Error {
            get {
                return ResourceManager.GetString("Addin_Login_Vesrion_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been logged out because there is a new version of the DealCloud Add In.  Please close and reopen [Outlook, Word or Excel] to update the DealCloud Add In to the latest version..
        /// </summary>
        public static string Addin_Logout_Version_Error {
            get {
                return ResourceManager.GetString("Addin_Logout_Version_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to logout?.
        /// </summary>
        public static string Are_you_sure_want_to_logout {
            get {
                return ResourceManager.GetString("Are_you_sure_want_to_logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap close_white_l {
            get {
                object obj = ResourceManager.GetObject("close_white_l", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dealcloud_l {
            get {
                object obj = ResourceManager.GetObject("dealcloud_l", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap error_m {
            get {
                object obj = ResourceManager.GetObject("error_m", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon error_m_red {
            get {
                object obj = ResourceManager.GetObject("error_m_red", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap folder_m {
            get {
                object obj = ResourceManager.GetObject("folder_m", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap load_s {
            get {
                object obj = ResourceManager.GetObject("load_s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap loading {
            get {
                object obj = ResourceManager.GetObject("loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap loading_blue {
            get {
                object obj = ResourceManager.GetObject("loading_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap log_file_m {
            get {
                object obj = ResourceManager.GetObject("log_file_m", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Error.
        /// </summary>
        public static string Network_Error {
            get {
                return ResourceManager.GetString("Network_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no access to {0} add-in functionality.
        /// </summary>
        public static string No_Access_To_0_Addin {
            get {
                return ResourceManager.GetString("No_Access_To_0_Addin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap refresh_m {
            get {
                object obj = ResourceManager.GetObject("refresh_m", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap report_m {
            get {
                object obj = ResourceManager.GetObject("report_m", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request timeout.
        /// </summary>
        public static string Request_timeout {
            get {
                return ResourceManager.GetString("Request_timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ability to quickly report issues.
        /// </summary>
        public static string RibbonDescriptionReport {
            get {
                return ResourceManager.GetString("RibbonDescriptionReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Issue.
        /// </summary>
        public static string RibbonLabelReport {
            get {
                return ResourceManager.GetString("RibbonLabelReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap search_m {
            get {
                object obj = ResourceManager.GetObject("search_m", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Expired.
        /// </summary>
        public static string Session_Expired {
            get {
                return ResourceManager.GetString("Session_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To use add-in please install IE with version 10 or upper..
        /// </summary>
        public static string To_use_addin_please_install_IE_with_version_10_or_upper {
            get {
                return ResourceManager.GetString("To_use_addin_please_install_IE_with_version_10_or_upper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VBA feature for office is not installed, please install it and then continue to use DealCloud Add-in.
        /// </summary>
        public static string VBA_feature_for_office_is_not_installed {
            get {
                return ResourceManager.GetString("VBA_feature_for_office_is_not_installed", resourceCulture);
            }
        }
    }
}
